In [5]:
from sklearn.datasets import load_iris
import numpy as np

In [9]:
# import 150 data from iris flower an X is featur an y is label

iris = load_iris()

X = iris.data

y = iris.target

X.shape, y.shape


# df = load_iris(as_frame=True)
# df

((150, 4), (150,))

In [10]:
iris.feature_names, iris.target_names

(['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'],
 array(['setosa', 'versicolor', 'virginica'], dtype='<U10'))

In [11]:
from sklearn.neighbors import KNeighborsClassifier

In [15]:
knn = KNeighborsClassifier(n_neighbors=1)
# k assume 5

knn.fit(X, y)

KNeighborsClassifier(n_neighbors=1)

In [16]:
a = np.array([3, 5, 4, 2]).reshape(1, 4)
knn.predict(a)

array([2])

In [17]:
b = np.array([[3, 5, 4, 2], [6, 4, 3, 2]]).reshape(2, -1)
knn.predict(b)

array([2, 1])

In [18]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X, y)
y_pred = knn.predict(b)

In [61]:
from sklearn.linear_model import LogisticRegression

In [63]:
logReg = LogisticRegression()
logReg.fit(X, y)
logReg.predict(b)

/Users/mhd/opt/anaconda3/lib/python3.9/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0, 1])