In [9]:
import pandas as pd
import numpy as np

In [66]:
df = pd.read_csv('stackoverflow/survey_results_public.csv')
people = {
    'first name': ['mohammad', 'mostafa', 'benyamin', None, np.nan, 'Na'],
    'last name': ['daraee', 'dana', 'dana', np.nan, 'alaie','Missing'],
    'email':['test@gmail.com', 'test3@gmail.com', 'test4@gmail.com', None, 'Missing', 'Missing'],
    'Age' :[23, 24, 19, np.nan, 'Missing', 'Na']
}
df3 = pd.DataFrame(people)
df3

first name last name            email      Age
0   mohammad    daraee   test@gmail.com       23
1    mostafa      dana  test3@gmail.com       24
2   benyamin      dana  test4@gmail.com       19
3       None       NaN             None      NaN
4        NaN     alaie          Missing  Missing
5         Na   Missing          Missing       Na

In [55]:
df2 = df.loc[0:30,['Country', 'YearsCode', 'ConvertedCompYearly']]
df2.head(5)

Country YearsCode  \
0                                           Slovakia       NaN   
1                                        Netherlands         7   
2                                 Russian Federation       NaN   
3                                            Austria       NaN   
4  United Kingdom of Great Britain and Northern I...        17   

   ConvertedCompYearly  
0              62268.0  
1                  NaN  
2                  NaN  
3                  NaN  
4                  NaN

In [20]:
df3.dropna()

first name last name            email Age
0   mohammad    daraee   test@gmail.com  23
1    mostafa      dana  test3@gmail.com  24
2   benyamin      dana  test4@gmail.com  19
5         Na   Missing          Missing  Na

In [22]:
df3.dropna(axis='columns')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5]

In [24]:
df3.dropna(how='all')

first name last name            email      Age
0   mohammad    daraee   test@gmail.com       23
1    mostafa      dana  test3@gmail.com       24
2   benyamin      dana  test4@gmail.com       19
4        NaN     alaie          Missing  Missing
5         Na   Missing          Missing       Na

In [25]:
df3.dropna(axis='columns', how='all')

first name last name            email      Age
0   mohammad    daraee   test@gmail.com       23
1    mostafa      dana  test3@gmail.com       24
2   benyamin      dana  test4@gmail.com       19
3       None       NaN             None      NaN
4        NaN     alaie          Missing  Missing
5         Na   Missing          Missing       Na

In [31]:
df3.dropna(axis='index', how='any', subset=['first name', 'email'])

first name last name            email Age
0   mohammad    daraee   test@gmail.com  23
1    mostafa      dana  test3@gmail.com  24
2   benyamin      dana  test4@gmail.com  19
5         Na   Missing          Missing  Na

In [37]:
df3['email'].unique()

array(['test@gmail.com', 'test3@gmail.com', 'test4@gmail.com', None, nan],
      dtype=object)

In [35]:
df3.replace('Missing', np.nan, inplace=True)

In [39]:
df3['Age'].unique()

array([23, 24, 19, nan, 'Na'], dtype=object)

In [40]:
df3.replace('Na', np.nan, inplace=True)
df3

first name last name            email   Age
0   mohammad    daraee   test@gmail.com  23.0
1    mostafa      dana  test3@gmail.com  24.0
2   benyamin      dana  test4@gmail.com  19.0
3       None       NaN             None   NaN
4        NaN     alaie              NaN   NaN
5        NaN       NaN              NaN   NaN

In [41]:
df3.isna()

first name  last name  email    Age
0       False      False  False  False
1       False      False  False  False
2       False      False  False  False
3        True       True   True   True
4        True      False   True   True
5        True       True   True   True

In [43]:
df3.dropna()

first name last name            email   Age
0   mohammad    daraee   test@gmail.com  23.0
1    mostafa      dana  test3@gmail.com  24.0
2   benyamin      dana  test4@gmail.com  19.0

In [44]:
df3

first name last name            email   Age
0   mohammad    daraee   test@gmail.com  23.0
1    mostafa      dana  test3@gmail.com  24.0
2   benyamin      dana  test4@gmail.com  19.0
3       None       NaN             None   NaN
4        NaN     alaie              NaN   NaN
5        NaN       NaN              NaN   NaN

In [46]:
df3.fillna('mimi')  # or any number or marker  

first name last name            email   Age
0   mohammad    daraee   test@gmail.com  23.0
1    mostafa      dana  test3@gmail.com  24.0
2   benyamin      dana  test4@gmail.com  19.0
3       mimi      mimi             mimi  mimi
4       mimi     alaie             mimi  mimi
5       mimi      mimi             mimi  mimi

In [53]:
df3.dtypes

first name     object
last name      object
email          object
Age           float64
dtype: object

In [56]:
df2.dtypes

Country                 object
YearsCode               object
ConvertedCompYearly    float64
dtype: object

In [59]:
# df2['YearsCode'].astype(int)   #return error

In [60]:
df2['YearsCode'].unique()

array([nan, '7', '17', '3', '4', '6', '16', '12', '15', '10', '40', '9',
       '26', '14', '39', '20'], dtype=object)

In [64]:
df2['YearsCode'] = df2['YearsCode'].astype(float)
df2['YearsCode'].mean()

14.24

In [79]:
df4 = pd.read_csv('survey_results_public.csv')
df4['YearsCode'].unique()

array([nan, '7', '17', '3', '4', '6', '16', '12', '15', '10', '40', '9',
       '26', '14', '39', '20', '8', '19', '5', 'Less than 1 year', '22',
       '2', '1', '34', '21', '13', '25', '24', '30', '31', '18', '38',
       'More than 50 years', '27', '41', '42', '35', '23', '28', '11',
       '37', '44', '43', '36', '33', '45', '29', '50', '46', '32', '47',
       '49', '48'], dtype=object)

In [80]:
# df4['YearsCode'].astype(float)  # return error for some str

In [82]:
df4['YearsCode'].replace('Less than 1 year', 0, inplace=True)
df4['YearsCode'].replace('More than 50 years', 51, inplace=True)
df4['YearsCode'].unique()

array([nan, '7', '17', '3', '4', '6', '16', '12', '15', '10', '40', '9',
       '26', '14', '39', '20', '8', '19', '5', 0, '22', '2', '1', '34',
       '21', '13', '25', '24', '30', '31', '18', '38', 51, '27', '41',
       '42', '35', '23', '28', '11', '37', '44', '43', '36', '33', '45',
       '29', '50', '46', '32', '47', '49', '48'], dtype=object)

In [87]:
df4['YearsCode'] = df4['YearsCode'].astype(float)
df4['YearsCode'].agg(['mean', 'median'])

mean      12.3382
median    10.0000
Name: YearsCode, dtype: float64