In [2]:
import numpy as np

In [11]:
a = np.arange(0, 10 ,2)
a

array([0, 2, 4, 6, 8])

In [15]:
b = np.linspace(0, 20, 5, retstep =True)
b

(array([ 0.,  5., 10., 15., 20.]), 5.0)

In [24]:
c = np.ones((3, 3, 4), dtype = int)
c

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [23]:
d = np.zeros((2, 3), dtype = int)
d

array([[0, 0, 0],
       [0, 0, 0]])

In [29]:
e = np.random.random((3, 4))
e

array([[0.89994386, 0.76208232, 0.58069293, 0.23704004],
       [0.00922157, 0.79679847, 0.7985381 , 0.66250692],
       [0.55149359, 0.64398218, 0.01437884, 0.3608326 ]])

In [34]:
g = np.random.randint(0, 10, (2, 3, 3))
g

array([[[5, 6, 1],
        [7, 3, 6],
        [8, 1, 6]],

       [[5, 5, 3],
        [1, 5, 4],
        [1, 4, 2]]])

In [42]:
np.random.seed(1)
f = np.random.randint(1, 9, (4, 3))
f

array([[6, 4, 5],
       [1, 8, 2],
       [4, 6, 8],
       [1, 1, 2]])