In [1]:
import numpy as np

In [2]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
b = np.append(a, [10, 12])
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12])

In [4]:
c = np.random.randint(0, 99, size =24).reshape(2, 3, 4)
c

array([[[40, 94, 26, 43],
        [30, 97, 97, 87],
        [74, 42,  2, 63]],

       [[61, 65, 21,  2],
        [89, 32,  8, 42],
        [12, 10, 82, 80]]])

In [5]:
g = np.random.randint(0, 99, size =24).reshape(2, 3, 4)
d = np.append(c , g, axis = 0)
d

array([[[40, 94, 26, 43],
        [30, 97, 97, 87],
        [74, 42,  2, 63]],

       [[61, 65, 21,  2],
        [89, 32,  8, 42],
        [12, 10, 82, 80]],

       [[71,  5, 20, 11],
        [26, 48, 44, 72],
        [15, 90, 53, 34]],

       [[ 4, 71, 50, 30],
        [86,  5, 92, 88],
        [57, 87, 76, 32]]])

In [29]:
f = np.append(c , g, axis = 2)
f

array([[[40, 94, 26, 43, 71,  5, 20, 11],
        [30, 97, 97, 87, 26, 48, 44, 72],
        [74, 42,  2, 63, 15, 90, 53, 34]],

       [[61, 65, 21,  2,  4, 71, 50, 30],
        [89, 32,  8, 42, 86,  5, 92, 88],
        [12, 10, 82, 80, 57, 87, 76, 32]]])

In [7]:
d.shape , f.shape

((4, 3, 4), (2, 3, 8))

In [31]:
h = np.insert(c, 2, [1, 2, 3, 4], axis = 1)
h

array([[[40, 94, 26, 43],
        [30, 97, 97, 87],
        [ 1,  2,  3,  4],
        [74, 42,  2, 63]],

       [[61, 65, 21,  2],
        [89, 32,  8, 42],
        [ 1,  2,  3,  4],
        [12, 10, 82, 80]]])

In [9]:
e = np.insert(c, 1,[1, 2, 3], axis= 2)
e

array([[[40,  1, 94, 26, 43],
        [30,  2, 97, 97, 87],
        [74,  3, 42,  2, 63]],

       [[61,  1, 65, 21,  2],
        [89,  2, 32,  8, 42],
        [12,  3, 10, 82, 80]]])

In [10]:
v = np.empty((2, 3, 4), dtype = int)   # its not initaling, faster than zeros or one
v

array([[[                  0, 7002943971834923003, 3702350794153222510,
         8392862729398479919],
        [8011685132709556072,          2037395059,                   0,
                           0],
        [                  0,                   0,                   0,
                           0]],

       [[                  0,                   0,                   0,
                           0],
        [                  0,                   0,                   0,
                           0],
        [                  0,                   0,                   0,
                           0]]])

In [11]:
np.copyto(v, c)   #copy c to v
v

array([[[40, 94, 26, 43],
        [30, 97, 97, 87],
        [74, 42,  2, 63]],

       [[61, 65, 21,  2],
        [89, 32,  8, 42],
        [12, 10, 82, 80]]])

In [2]:
c

NameError: name 'c' is not defined

In [12]:
m = np.delete(c, 0 , axis=0)
m

array([[[61, 65, 21,  2],
        [89, 32,  8, 42],
        [12, 10, 82, 80]]])

In [13]:
n = np.delete(c, 0 , axis=1)
n

array([[[30, 97, 97, 87],
        [74, 42,  2, 63]],

       [[89, 32,  8, 42],
        [12, 10, 82, 80]]])

In [14]:
x = np.delete(c, 1 , axis=2)
x

array([[[40, 26, 43],
        [30, 97, 87],
        [74,  2, 63]],

       [[61, 21,  2],
        [89,  8, 42],
        [12, 82, 80]]])

In [15]:
aa = np.arange(12).reshape(3, 4)
bb = np.arange(13, 25).reshape(3, 4)
aa

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
bb

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [17]:
cc = np.concatenate((aa, bb), axis = 0)
cc

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [18]:
stack0 = np.stack((aa, bb), axis = 0)
stack1 = np.stack((aa, bb), axis = 1)
stack2 = np.stack((aa, bb), axis = 2)
stack0

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [19]:
stack1

array([[[ 0,  1,  2,  3],
        [13, 14, 15, 16]],

       [[ 4,  5,  6,  7],
        [17, 18, 19, 20]],

       [[ 8,  9, 10, 11],
        [21, 22, 23, 24]]])

In [20]:
stack2

array([[[ 0, 13],
        [ 1, 14],
        [ 2, 15],
        [ 3, 16]],

       [[ 4, 17],
        [ 5, 18],
        [ 6, 19],
        [ 7, 20]],

       [[ 8, 21],
        [ 9, 22],
        [10, 23],
        [11, 24]]])

In [21]:
ee = np.random.randint(1, 99, size = 40).reshape(4, 2, 5)
ee

array([[[37, 24,  2, 35, 52],
        [96, 14, 77, 86, 19]],

       [[79, 69, 83, 89, 35],
        [11, 73, 98, 90,  6]],

       [[74, 33, 23, 74,  9],
        [98, 52, 32, 48, 97]],

       [[88, 21, 52,  3, 65],
        [59, 49, 32, 27, 22]]])

In [22]:
split0 = np.split(ee, 1, axis = 0)
split00 = np.split(ee, 4, axis = 0)
split1 = np.split(ee, 2, axis = 1)
split2 = np.split(ee, 5, axis = 2)
split0

[array([[[37, 24,  2, 35, 52],
         [96, 14, 77, 86, 19]],
 
        [[79, 69, 83, 89, 35],
         [11, 73, 98, 90,  6]],
 
        [[74, 33, 23, 74,  9],
         [98, 52, 32, 48, 97]],
 
        [[88, 21, 52,  3, 65],
         [59, 49, 32, 27, 22]]])]

In [23]:
split00

[array([[[37, 24,  2, 35, 52],
         [96, 14, 77, 86, 19]]]),
 array([[[79, 69, 83, 89, 35],
         [11, 73, 98, 90,  6]]]),
 array([[[74, 33, 23, 74,  9],
         [98, 52, 32, 48, 97]]]),
 array([[[88, 21, 52,  3, 65],
         [59, 49, 32, 27, 22]]])]

In [24]:
ccc = np.array(split00)
ccc.shape

(4, 1, 2, 5)

In [25]:
split1

[array([[[37, 24,  2, 35, 52]],
 
        [[79, 69, 83, 89, 35]],
 
        [[74, 33, 23, 74,  9]],
 
        [[88, 21, 52,  3, 65]]]),
 array([[[96, 14, 77, 86, 19]],
 
        [[11, 73, 98, 90,  6]],
 
        [[98, 52, 32, 48, 97]],
 
        [[59, 49, 32, 27, 22]]])]

In [26]:
split2

[array([[[37],
         [96]],
 
        [[79],
         [11]],
 
        [[74],
         [98]],
 
        [[88],
         [59]]]),
 array([[[24],
         [14]],
 
        [[69],
         [73]],
 
        [[33],
         [52]],
 
        [[21],
         [49]]]),
 array([[[ 2],
         [77]],
 
        [[83],
         [98]],
 
        [[23],
         [32]],
 
        [[52],
         [32]]]),
 array([[[35],
         [86]],
 
        [[89],
         [90]],
 
        [[74],
         [48]],
 
        [[ 3],
         [27]]]),
 array([[[52],
         [19]],
 
        [[35],
         [ 6]],
 
        [[ 9],
         [97]],
 
        [[65],
         [22]]])]

In [27]:
np.array(split2).shape

(5, 4, 2, 1)