In [1]:
import numpy as np

In [2]:
def cal_squar(n):
    return n * n

In [7]:
cal_squar

<function __main__.cal_squar(n)>

In [8]:
np.testing.assert_equal(cal_squar(5), 24)    #test for funstion that are equal

AssertionError: 
Items are not equal:
 ACTUAL: 25
 DESIRED: 24

In [8]:
np_func = np.frompyfunc(cal_squar, 1 ,1)

In [13]:
a = np.arange(10)
np_func(a)

array([0, 1, 4, 9, 16, 25, 36, 49, 64, 81], dtype=object)

In [14]:
b = np.outer(a, a)    #multiple row and column
b

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [17]:
bb = np.outer(a, [1, 2, 3, 4])
bb

array([[ 0,  0,  0,  0],
       [ 1,  2,  3,  4],
       [ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16],
       [ 5, 10, 15, 20],
       [ 6, 12, 18, 24],
       [ 7, 14, 21, 28],
       [ 8, 16, 24, 32],
       [ 9, 18, 27, 36]])

In [18]:
np_func(b)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 4, 9, 16, 25, 36, 49, 64, 81],
       [0, 4, 16, 36, 64, 100, 144, 196, 256, 324],
       [0, 9, 36, 81, 144, 225, 324, 441, 576, 729],
       [0, 16, 64, 144, 256, 400, 576, 784, 1024, 1296],
       [0, 25, 100, 225, 400, 625, 900, 1225, 1600, 2025],
       [0, 36, 144, 324, 576, 900, 1296, 1764, 2304, 2916],
       [0, 49, 196, 441, 784, 1225, 1764, 2401, 3136, 3969],
       [0, 64, 256, 576, 1024, 1600, 2304, 3136, 4096, 5184],
       [0, 81, 324, 729, 1296, 2025, 2916, 3969, 5184, 6561]],
      dtype=object)

In [19]:
np.mod(10, 4), 10 % 4

(2, 2)

In [12]:
x = np.sqrt(5)
np.mod(x , 1)       # is numer a int number

0.2360679774997898

In [21]:
eq = np.equal(2, 3)     #like test.asert_equal but return boolean
eq

False

In [22]:
s = np.arange(10)
d = np.arange(10)
s

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
g = np.outer(s, d)
g

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36],
       [ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45],
       [ 0,  6, 12, 18, 24, 30, 36, 42, 48, 54],
       [ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63],
       [ 0,  8, 16, 24, 32, 40, 48, 56, 64, 72],
       [ 0,  9, 18, 27, 36, 45, 54, 63, 72, 81]])

In [28]:
sub = np.subtract(s, d)
mul = np.multiply(s, d)
sub, mul

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81]))

In [30]:
ad = np.add.outer(s, d)
ad

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
       [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [32]:
div = np.divide.outer(s, d + 1)
div

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
        0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ],
       [2.        , 1.        , 0.66666667, 0.5       , 0.4       ,
        0.33333333, 0.28571429, 0.25      , 0.22222222, 0.2       ],
       [3.        , 1.5       , 1.        , 0.75      , 0.6       ,
        0.5       , 0.42857143, 0.375     , 0.33333333, 0.3       ],
       [4.        , 2.        , 1.33333333, 1.        , 0.8       ,
        0.66666667, 0.57142857, 0.5       , 0.44444444, 0.4       ],
       [5.        , 2.5       , 1.66666667, 1.25      , 1.        ,
        0.83333333, 0.71428571, 0.625     , 0.55555556, 0.5       ],
       [6.        , 3.        , 2.        , 1.5       , 1.2       ,
        1.        , 0.85714286, 0.75      , 0.66666667, 0.6       ],
       [7.        , 3.5       , 2.3333333

In [13]:
def is_int(x):
    return np.equal(np.mod(x, 1), 0)

In [14]:
np_func_int = np.frompyfunc(is_int, 1, 1)

In [15]:
np_func_int([1, 2 ,3])

array([True, True, True], dtype=object)

In [18]:
ss = np.arange(9) + 1
dd = np.arange(9) + 1

In [19]:
result= np.add.outer(ss ** 2 , dd ** 2)
result

array([[  2,   5,  10,  17,  26,  37,  50,  65,  82],
       [  5,   8,  13,  20,  29,  40,  53,  68,  85],
       [ 10,  13,  18,  25,  34,  45,  58,  73,  90],
       [ 17,  20,  25,  32,  41,  52,  65,  80,  97],
       [ 26,  29,  34,  41,  50,  61,  74,  89, 106],
       [ 37,  40,  45,  52,  61,  72,  85, 100, 117],
       [ 50,  53,  58,  65,  74,  85,  98, 113, 130],
       [ 65,  68,  73,  80,  89, 100, 113, 128, 145],
       [ 82,  85,  90,  97, 106, 117, 130, 145, 162]])

In [20]:
res = np_func_int(np.sqrt(result))
res

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, True, False, False, False, False, False],
       [False, False, True, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, True, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, True, False, False, False],
       [False, False, False, False, False, False, False, False, False]],
      dtype=object)

In [81]:
x = []
row = 0
column = 0
for item in res:
    for i in item:
        if i == True:
            x.append(result[row, column])
            print(row, column)
        column += 1
    row += 1
    column = 0
x

2 3
3 2
5 7
7 5


[25, 25, 100, 100]