In [1]:
import numpy as np

In [2]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [3]:
b = np.arange(1, 21)
b.shape = (5, 4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [4]:
b[0][2]

3

In [5]:
b[0, 2]

3

In [6]:
b[:,:2]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10],
       [13, 14],
       [17, 18]])

In [7]:
e = np.random.randint(1, 9, size=(2, 3, 4))
e

array([[[2, 7, 1, 1],
        [7, 3, 2, 7],
        [7, 8, 5, 8]],

       [[7, 4, 2, 6],
        [2, 3, 4, 8],
        [5, 1, 6, 8]]])

In [8]:
e[0]

array([[2, 7, 1, 1],
       [7, 3, 2, 7],
       [7, 8, 5, 8]])

In [9]:
e[0, 1]

array([7, 3, 2, 7])

In [10]:
e[0, 1, -1]

7

In [11]:
e[1, 1, 0]

2

In [12]:
e[:,:,-2:]

array([[[1, 1],
        [2, 7],
        [5, 8]],

       [[2, 6],
        [4, 8],
        [6, 8]]])

In [13]:
np.random.seed(1)
d = np.random.randint(0, 10, size=(2, 2, 3, 5))
d

array([[[[5, 8, 9, 5, 0],
         [0, 1, 7, 6, 9],
         [2, 4, 5, 2, 4]],

        [[2, 4, 7, 7, 9],
         [1, 7, 0, 6, 9],
         [9, 7, 6, 9, 1]]],


       [[[0, 1, 8, 8, 3],
         [9, 8, 7, 3, 6],
         [5, 1, 9, 3, 4]],

        [[8, 1, 4, 0, 3],
         [9, 2, 0, 4, 9],
         [2, 7, 7, 9, 8]]]])

In [14]:
d[0, 1, 2, 1]

7

In [15]:
d

array([[[[5, 8, 9, 5, 0],
         [0, 1, 7, 6, 9],
         [2, 4, 5, 2, 4]],

        [[2, 4, 7, 7, 9],
         [1, 7, 0, 6, 9],
         [9, 7, 6, 9, 1]]],


       [[[0, 1, 8, 8, 3],
         [9, 8, 7, 3, 6],
         [5, 1, 9, 3, 4]],

        [[8, 1, 4, 0, 3],
         [9, 2, 0, 4, 9],
         [2, 7, 7, 9, 8]]]])