In [1]:
import numpy as np

In [4]:
first_array = np.arange(1,25).reshape(2, 3, 4)
first_array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [5]:
second_array = first_array   #deep copy
second_array

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [6]:
first_array == second_array

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [7]:
first_array is second_array

True

In [8]:
id(first_array), id(second_array)

(140542067780272, 140542067780272)

In [9]:
first_array[1, 0, 0] = 100
first_array

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[100,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [10]:
second_array

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[100,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [11]:
third_array = first_array.view()   #shalow copy
third_array

array([[[  1,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[100,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [12]:
third_array == first_array

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [14]:
third_array is first_array

False

In [15]:
first_array[0, 0, 0] = 540
first_array

array([[[540,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[100,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [16]:
third_array

array([[[540,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[100,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [19]:
forth_array = np.copy(first_array)
forth_array

array([[[540,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[100,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])

In [18]:
forth_array 

array([[[540,   2,   3,   4],
        [  5,   6,   7,   8],
        [  9,  10,  11,  12]],

       [[100,  14,  15,  16],
        [ 17,  18,  19,  20],
        [ 21,  22,  23,  24]]])