In [1]:
import numpy as np

In [2]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [3]:
a + 4

array([4, 5, 6, 7, 8])

In [4]:
b = np.random.randint(1, 9, size = 5).reshape(1, 5)
b

array([[4, 6, 2, 4, 8]])

In [5]:
a + b

array([[ 4,  6,  9, 10,  6]])

In [6]:
a * b

array([[ 0,  5, 14, 21,  8]])

In [7]:
a % b

array([[0, 1, 2, 3, 0]])

In [8]:
a // b

array([[0, 0, 0, 0, 2]])

In [9]:
a / b

array([[0.        , 0.2       , 0.28571429, 0.42857143, 2.        ]])

In [13]:
c = np.random.randint(1, 99, size = 50).reshape(10, 5)
c

array([[78, 91, 34, 42, 59],
       [ 2, 27, 24, 49, 32],
       [73, 85, 48, 68, 30],
       [58,  5, 26, 94, 98],
       [25, 11, 29, 35, 11],
       [37, 19, 89, 31, 73],
       [71, 93, 64,  6, 66],
       [25, 58, 53, 81, 76],
       [57, 28, 27, 30,  9],
       [91, 41,  7,  3, 97]])

In [14]:
b.shape , c.shape

((1, 5), (10, 5))

In [15]:
b + c

array([[ 82,  96,  41,  49,  61],
       [  6,  32,  31,  56,  34],
       [ 77,  90,  55,  75,  32],
       [ 62,  10,  33, 101, 100],
       [ 29,  16,  36,  42,  13],
       [ 41,  24,  96,  38,  75],
       [ 75,  98,  71,  13,  68],
       [ 29,  63,  60,  88,  78],
       [ 61,  33,  34,  37,  11],
       [ 95,  46,  14,  10,  99]])

In [16]:
b

array([[4, 5, 7, 7, 2]])

In [19]:
d = np.arange(5).reshape(5, 1)
d

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [20]:
b.shape, d.shape  # if we have roe or column == each other or ... they can expand

((1, 5), (5, 1))

In [21]:
b + d

array([[ 4,  5,  7,  7,  2],
       [ 5,  6,  8,  8,  3],
       [ 6,  7,  9,  9,  4],
       [ 7,  8, 10, 10,  5],
       [ 8,  9, 11, 11,  6]])

In [9]:
e = np.random.randint(1, 99, size = 40).reshape(2, 5, 4)
e

array([[[88, 19, 35, 84],
        [54, 15, 74, 93],
        [12, 67, 92, 79],
        [19, 39, 41, 54],
        [26, 74, 95, 97]],

       [[86, 17, 62, 39],
        [36,  9, 20, 49],
        [69, 13, 23, 31],
        [11, 28,  4, 23],
        [63, 59, 58, 91]]])

In [10]:
array = np.arange(20).reshape(5 ,4)
array


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [11]:
array + e

array([[[ 88,  20,  37,  87],
        [ 58,  20,  80, 100],
        [ 20,  76, 102,  90],
        [ 31,  52,  55,  69],
        [ 42,  91, 113, 116]],

       [[ 86,  18,  64,  42],
        [ 40,  14,  26,  56],
        [ 77,  22,  33,  42],
        [ 23,  41,  18,  38],
        [ 79,  76,  76, 110]]])

In [12]:
e

array([[[88, 19, 35, 84],
        [54, 15, 74, 93],
        [12, 67, 92, 79],
        [19, 39, 41, 54],
        [26, 74, 95, 97]],

       [[86, 17, 62, 39],
        [36,  9, 20, 49],
        [69, 13, 23, 31],
        [11, 28,  4, 23],
        [63, 59, 58, 91]]])

In [13]:
np.mean(e)     #miangin

48.7

In [15]:
np.median(e)  #miane

45.0

In [16]:
np.max(e), np.min(e), np.var(e)  # max min var

(97, 4, 834.5099999999999)

In [17]:
np.std(e)    #enheraf meyar == jazr var

28.88788673475441

In [14]:
np.sum(e)/ e.size

48.7

In [20]:
np.sum([((x - np.mean(e)) ** 2) for x in e]) / (e.size - 1)

855.9076923076922

In [43]:
np.var(e)

790.01