In [1]:
import numpy as np

In [2]:
my_vector = np.arange(6)
my_2D_vector = np.arange(12).reshape(3, 4)
my_3D_vector = np.arange(24).reshape(2, 3, 4)
my_vector

array([0, 1, 2, 3, 4, 5])

In [3]:
my_2D_vector

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
my_3D_vector

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [5]:
np.transpose(my_vector)

array([0, 1, 2, 3, 4, 5])

In [6]:
np.transpose(my_2D_vector)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [9]:
np.transpose(my_vector.reshape(1, 6))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [10]:
np.transpose(my_3D_vector)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [12]:
np.transpose(my_3D_vector, axes=(0, 1, 2))

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [14]:
result = np.transpose(my_3D_vector, axes=(2, 0 ,1))
result

array([[[ 0,  4,  8],
        [12, 16, 20]],

       [[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]]])

In [15]:
my_3D_vector.shape, result.shape

((2, 3, 4), (4, 2, 3))

In [16]:
result0 = np.transpose(my_3D_vector, axes=(2, 1 ,0))
result0

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [17]:
my_3D_vector.shape, result0.shape

((2, 3, 4), (4, 3, 2))

In [18]:
np.swapaxes(my_3D_vector, 1 , 0)   #change array place

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [20]:
moved = np.moveaxis(my_3D_vector, 1, 2)
moved

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

In [21]:
my_3D_vector.shape, moved.shape

((2, 3, 4), (2, 4, 3))

In [22]:
moved0 = np.moveaxis(my_3D_vector, 2, 0)   #move select axis to any other axes and move other axis forward
moved0

array([[[ 0,  4,  8],
        [12, 16, 20]],

       [[ 1,  5,  9],
        [13, 17, 21]],

       [[ 2,  6, 10],
        [14, 18, 22]],

       [[ 3,  7, 11],
        [15, 19, 23]]])

In [23]:
my_3D_vector.shape, moved0.shape

((2, 3, 4), (4, 2, 3))

In [25]:
a = np.random.randint(0, 99, size =(3, 4))
b = np.random.randint(0, 99, size =(3, 4))
a

array([[22, 16,  3, 51],
       [52, 96, 62, 55],
       [81, 79, 14, 71]])

In [26]:
b

array([[90, 81, 13, 11],
       [ 4, 55, 32, 81],
       [39, 83, 56, 95]])

In [27]:
a * b

array([[1980, 1296,   39,  561],
       [ 208, 5280, 1984, 4455],
       [3159, 6557,  784, 6745]])

In [28]:
np.dot(a, b)     #zarb matrix

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [29]:
b.shape = (4,3)

In [30]:
np.dot(a, b)

array([[ 6485,  4945,  6128],
       [12285, 12698, 13599],
       [14500, 11987, 12689]])

In [ ]:
np.do