In [1]:
import numpy as np

In [5]:
a = np.arange(10)
b = np.arange(12).reshape(3, 4)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
np.tile(a, 3)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1,
       2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.tile(a, 3).reshape(3, a.size)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [10]:
np.tile(a, (1, 1))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [14]:
np.tile(a, (1, 2))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [15]:
np.tile(a, (2, 2))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [16]:
np.tile(a, (3, 2, 2))

array([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

       [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]],

       [[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
        [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])

In [17]:
np.tile(b, (2, 2))

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [18]:
np.repeat(a, 2)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6, 7, 7, 8, 8, 9, 9])

In [23]:
np.repeat(b, 2, axis=0)

array([[ 0,  1,  2,  3],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 8,  9, 10, 11]])

In [21]:
np.repeat(b, 2, axis=1)

array([[ 0,  0,  1,  1,  2,  2,  3,  3],
       [ 4,  4,  5,  5,  6,  6,  7,  7],
       [ 8,  8,  9,  9, 10, 10, 11, 11]])

In [3]:
c = np.random.randint(99, size=10)
d = np.random.randint(99, size=(3, 4))
c

array([11, 44, 66, 85, 51, 81, 18, 95, 38, 17])

In [4]:
d

array([[85,  9, 11, 83],
       [26, 98, 57, 70],
       [85, 57, 92, 47]])

In [27]:
np.sort(c)

array([11, 30, 31, 31, 57, 58, 59, 72, 92, 94])

In [28]:
np.sort(d)

array([[32, 40, 40, 96],
       [ 3, 33, 48, 94],
       [ 4, 22, 36, 64]])

In [30]:
np.sort(d, axis=0)

array([[22,  3, 32, 36],
       [40,  4, 33, 48],
       [94, 40, 64, 96]])

In [31]:
np.sort(d, axis=1)

array([[32, 40, 40, 96],
       [ 3, 33, 48, 94],
       [ 4, 22, 36, 64]])

In [32]:
np.argsort(c)   #show index od min to max number

array([2, 7, 0, 3, 9, 1, 6, 5, 4, 8])

In [33]:
np.argsort(d)

array([[2, 0, 1, 3],
       [1, 2, 3, 0],
       [1, 0, 3, 2]])

In [34]:
np.argsort(d, axis=0)

array([[2, 1, 0, 2],
       [0, 2, 1, 1],
       [1, 0, 2, 0]])

In [5]:
d

array([[85,  9, 11, 83],
       [26, 98, 57, 70],
       [85, 57, 92, 47]])

In [6]:
np.argmax(d), np.argmin(d)   # show index of max and max

(5, 1)

In [7]:
np.argmax(d, axis=1)    # show max index in every row

array([0, 1, 2])

In [9]:
np.argmax(d, axis=0)

array([0, 1, 2, 0])