In [17]:
import numpy as np

In [18]:
my_array = np.arange(24)
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [19]:
my_array.reshape(2, 3, 4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [20]:
my_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [21]:
my_array.shape = (2, 3, 4)

In [22]:
my_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [23]:
reshape_array = my_array.reshape((2, 12))
reshape_array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

In [24]:
reshape_array[0, 0] = 1234
reshape_array

array([[1234,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
          11],
       [  12,   13,   14,   15,   16,   17,   18,   19,   20,   21,   22,
          23]])

In [25]:
my_array

array([[[1234,    1,    2,    3],
        [   4,    5,    6,    7],
        [   8,    9,   10,   11]],

       [[  12,   13,   14,   15],
        [  16,   17,   18,   19],
        [  20,   21,   22,   23]]])

In [28]:
my_array is reshape_array

False

In [29]:
ravel_array = np.ravel(my_array)   #make a vector of any array   its a view
ravel_array

array([1234,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

In [32]:
flatten_array = my_array.flatten()    #it's not a view its' copy that changes can't effect
flatten_array

array([1234,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

In [33]:
ravel_array[1] = 155
my_array

array([[[1234,  155,    2,    3],
        [   4,    5,    6,    7],
        [   8,    9,   10,   11]],

       [[  12,   13,   14,   15],
        [  16,   17,   18,   19],
        [  20,   21,   22,   23]]])

In [34]:
flatten_array

array([1234,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,   16,   17,   18,   19,   20,   21,
         22,   23])

In [35]:
my_array is ravel_array

False

In [36]:
flatten_array[2] = 250
my_array

array([[[1234,  155,    2,    3],
        [   4,    5,    6,    7],
        [   8,    9,   10,   11]],

       [[  12,   13,   14,   15],
        [  16,   17,   18,   19],
        [  20,   21,   22,   23]]])

In [38]:
flat_array = my_array.flat       #make an array iterator and can use next()
flat_array , list(flat_array)

(<numpy.flatiter at 0x7f9b7e00d200>,
 [1234,
  155,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23])

In [39]:
my_array

array([[[1234,  155,    2,    3],
        [   4,    5,    6,    7],
        [   8,    9,   10,   11]],

       [[  12,   13,   14,   15],
        [  16,   17,   18,   19],
        [  20,   21,   22,   23]]])

In [45]:
my_array.shape = (4, 6)
my_array[0, 0] = 0
my_array[0, 1] = 1
my_array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [46]:
my_3D_array = np.arange(24).reshape(2, 3, 4)
my_3D_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [47]:
np.fliplr(my_array)

array([[ 5,  4,  3,  2,  1,  0],
       [11, 10,  9,  8,  7,  6],
       [17, 16, 15, 14, 13, 12],
       [23, 22, 21, 20, 19, 18]])

In [48]:
np.fliplr(my_3D_array)

array([[[ 8,  9, 10, 11],
        [ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[20, 21, 22, 23],
        [16, 17, 18, 19],
        [12, 13, 14, 15]]])

In [49]:
np.flipud(my_array)

array([[18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [50]:
np.flipud(my_3D_array)

array([[[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]])

In [52]:
np.roll(my_array, 5)

array([[19, 20, 21, 22, 23,  0],
       [ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18]])

In [53]:
np.roll(my_3D_array, -3)

array([[[ 3,  4,  5,  6],
        [ 7,  8,  9, 10],
        [11, 12, 13, 14]],

       [[15, 16, 17, 18],
        [19, 20, 21, 22],
        [23,  0,  1,  2]]])

In [54]:
np.rot90(my_array)

array([[ 5, 11, 17, 23],
       [ 4, 10, 16, 22],
       [ 3,  9, 15, 21],
       [ 2,  8, 14, 20],
       [ 1,  7, 13, 19],
       [ 0,  6, 12, 18]])

In [58]:
my_array

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [55]:
np.rot90(my_3D_array)

array([[[ 8,  9, 10, 11],
        [20, 21, 22, 23]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 0,  1,  2,  3],
        [12, 13, 14, 15]]])

In [56]:
my_3D_array

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [59]:
my_3D_array.shape

(2, 3, 4)