In [3]:
import numpy as np

In [4]:
a = np.random.randint(1, 100, size = 60)
a

array([83, 78, 91, 70,  6,  7, 77, 92,  7, 18, 98, 96, 65, 43, 86, 49, 41,
       42, 48, 46, 30, 84, 19, 94, 54,  5, 41, 92, 52, 19, 23, 23, 91, 43,
       48,  7, 20, 85, 28, 91, 85,  8,  1, 77,  9, 51,  7, 47, 15,  5, 33,
       42, 40, 84, 40,  8, 45, 14, 22,  3])

In [6]:
a.shape

(60,)

In [7]:
a = a.reshape(1, 60)
a.shape

(1, 60)

In [9]:
a = a.reshape((2, 5, 6))
a

array([[[83, 78, 91, 70,  6,  7],
        [77, 92,  7, 18, 98, 96],
        [65, 43, 86, 49, 41, 42],
        [48, 46, 30, 84, 19, 94],
        [54,  5, 41, 92, 52, 19]],

       [[23, 23, 91, 43, 48,  7],
        [20, 85, 28, 91, 85,  8],
        [ 1, 77,  9, 51,  7, 47],
        [15,  5, 33, 42, 40, 84],
        [40,  8, 45, 14, 22,  3]]])

In [10]:
unique_array = np.unique(a)
unique_array

array([ 1,  3,  5,  6,  7,  8,  9, 14, 15, 18, 19, 20, 22, 23, 28, 30, 33,
       40, 41, 42, 43, 45, 46, 47, 48, 49, 51, 52, 54, 65, 70, 77, 78, 83,
       84, 85, 86, 91, 92, 94, 96, 98])

In [11]:
a[0, :, -2:]

array([[ 6,  7],
       [98, 96],
       [41, 42],
       [19, 94],
       [52, 19]])

In [7]:
a[a>30]

array([87, 45, 82, 31, 90, 40, 31, 75, 98, 53, 60, 89, 44, 83, 99, 92, 36,
       78, 90, 95, 38, 74, 57, 32, 35, 80, 68, 71, 51, 86, 58, 67, 65, 57,
       51, 81, 62, 63, 90, 87, 35, 38, 51, 58, 45, 89, 86])

In [8]:
greater_than_30 = a >30
greater_than_30

array([[[ True,  True,  True,  True,  True,  True],
        [ True,  True, False,  True,  True,  True],
        [ True, False,  True,  True,  True,  True],
        [ True, False,  True, False,  True,  True],
        [ True,  True,  True, False, False, False]],

       [[False, False,  True,  True, False, False],
        [ True,  True,  True,  True, False,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True, False,  True,  True,  True]]])

In [9]:
a|a>30

array([[[ True,  True,  True,  True,  True,  True],
        [ True,  True, False,  True,  True,  True],
        [ True, False,  True,  True,  True,  True],
        [ True, False,  True, False,  True,  True],
        [ True,  True,  True, False, False, False]],

       [[False, False,  True,  True, False, False],
        [ True,  True,  True,  True, False,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True],
        [ True,  True, False,  True,  True,  True]]])

In [10]:
a[greater_than_30]

array([87, 45, 82, 31, 90, 40, 31, 75, 98, 53, 60, 89, 44, 83, 99, 92, 36,
       78, 90, 95, 38, 74, 57, 32, 35, 80, 68, 71, 51, 86, 58, 67, 65, 57,
       51, 81, 62, 63, 90, 87, 35, 38, 51, 58, 45, 89, 86])

In [11]:
even_in_a = a % 2 == 0
even_in_a

array([[[False, False,  True, False,  True,  True],
        [False, False,  True,  True, False,  True],
        [False, False,  True, False, False,  True],
        [ True, False,  True,  True,  True, False],
        [ True,  True, False,  True,  True,  True]],

       [[ True, False,  True, False,  True, False],
        [ True,  True, False, False,  True,  True],
        [ True, False, False, False, False, False],
        [ True, False,  True, False, False,  True],
        [False,  True, False, False, False,  True]]])

In [12]:
a[even_in_a]

array([82, 90, 40,  8, 98, 60, 44, 92, 36, 78, 26, 90, 38, 74, 16, 10, 28,
       20, 32, 14, 80, 68, 14, 86, 58, 62, 90, 38, 58, 86])

In [13]:
final_mask = np.logical_and(greater_than_30, even_in_a)
a[final_mask]

array([82, 90, 40, 98, 60, 44, 92, 36, 78, 90, 38, 74, 32, 80, 68, 86, 58,
       62, 90, 38, 58, 86])

In [14]:
less_than_20 = a<20
result = np.logical_or(greater_than_30, less_than_20)
a[result]

array([87, 45, 82, 31, 90, 40, 31, 75,  8, 98, 53, 60, 89,  7, 44, 83, 99,
       92, 36, 78, 90, 95, 38, 74, 57, 16, 10, 32, 35, 14, 13, 80, 68, 71,
       51, 14, 86, 58, 67, 65, 57, 51, 81, 62, 63, 90, 87, 35, 38, 51, 58,
       19, 45, 89, 86])

In [29]:
a | a % 2 == 0

array([[[False, False, False, False, False, False],
        [False, False, False, False, False, False],
        [False, False, False, False, False, False],
        [False, False, False, False, False, False],
        [False, False, False, False, False, False]],

       [[False, False, False, False, False, False],
        [False, False, False, False, False, False],
        [False, False, False, False, False, False],
        [False, False, False, False, False, False],
        [False, False, False, False, False, False]]])

In [18]:
10 % 3

1